import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../providers/themeProvider";
import { StoreProvider } from "../providers/storeProvider";
import { Toaster } from "@/components/ui/toaster";
import SessionProviderWrapper from "../providers/sessionProvider";
import SocketWrapper from "@/providers/socketProvider";

const inter = Inter({ display: "swap", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper>
          <StoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SocketWrapper>
                {children}
                <Toaster />
              </SocketWrapper>
            </ThemeProvider>
          </StoreProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
